[tool.poetry]
name = "pytest-serverless"
version = "0.1.0"
description = ""
authors = ["Daniel Ancuta <whisller@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
pytest = "^4.5"
pyyaml = "^5.1"
moto = "^1.3"
boto3 = "^1.9"

[tool.poetry.dev-dependencies]

[tool.poetry.plugins."pytest11"]
"serverless" = "pytest_serverless"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

